import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:isar/isar.dart';
import '../../../services/supabase_service.dart';
import '../../../services/isar_service.dart';
import '../../../models/resource_point.dart';

final isarServiceProvider = Provider<IsarService>((ref) {
  return IsarService();
});

final resourceRepositoryProvider = Provider<ResourceRepository>((ref) {
  final isarService = ref.watch(isarServiceProvider);
  return ResourceRepository(SupabaseService.client, isarService);
});

class ResourceRepository {
  final SupabaseClient _supabase;
  final IsarService _isarService;

  ResourceRepository(this._supabase, this._isarService);

  // Fetch resources from Supabase and cache them locally
  Future<List<ResourcePoint>> getResources() async {
    try {
      // 1. Try to fetch from Supabase (Network First)
      final data = await _supabase
          .from('resource_points')
          .select()
          .eq('isActive', true); // Only fetch active resources

      final resources = (data as List)
          .map((json) => ResourcePoint.fromJson(json))
          .toList();

      // Web: Isar 3.x has no web support; skip caching.
      if (kIsWeb) {
        return resources;
      }

      // 2. Cache to Isar
      final isar = await _isarService.db;
      await isar.writeTxn(() async {
        await isar.resourcePoints.putAll(resources);
      });

      return resources;
    } catch (e) {
      if (kIsWeb) rethrow;
      // 3. Fallback to Isar (Offline)
      final isar = await _isarService.db;
      return await isar.resourcePoints.where().findAll();
    }
  }

  // Create a new resource point
  Future<void> createResourcePoint(ResourcePoint resource) async {
    // 1. Upload to Supabase
    final data = resource.toJson();
    // Remove ID if it's generated by Supabase, or keep it if we generate it locally.
    // Assuming Supabase generates ID, but we might need UUID for offline creation.
    // For now, let's assume we send the ID.
    
    await _supabase.from('resource_points').insert(data);

    // 2. Save to local cache (native only)
    if (!kIsWeb) {
      final isar = await _isarService.db;
      await isar.writeTxn(() async {
        await isar.resourcePoints.put(resource);
      });
    }
  }
}
